In [1]:
import numpy as np
import pandas as pd

In [2]:
mydf = pd.DataFrame({"Name": ["Mary", "Jane", "Bill", "Tom"], "Age": [19, 20, 30, 40], "Grade": [90, 87, 75, 95], "Sex": ["female", "female", "male", "male"]})

In [3]:
mydf

   Name  Age  Grade     Sex
0  Mary   19     90  female
1  Jane   20     87  female
2  Bill   30     75    male
3   Tom   40     95    male

In [4]:
grades = mydf.groupby("Sex")[["Grade"]].mean()

In [5]:
b = grades.reset_index()
b

      Sex  Grade
0  female   88.5
1    male   85.0

In [6]:
mydf.to_csv("grade_data.csv")

In [7]:
mydf2 = pd.read_csv("grade_data.csv").iloc[:,1:]

In [8]:
mydf2

   Name  Age  Grade     Sex
0  Mary   19     90  female
1  Jane   20     87  female
2  Bill   30     75    male
3   Tom   40     95    male

In [9]:
mydf2 = pd.read_csv("grade_data.csv", usecols = ["Name", "Age", "Grade", "Sex"], index_col = "Name")

In [10]:
mydf2

      Age  Grade     Sex
Name
Mary   19     90  female
Jane   20     87  female
Bill   30     75    male
Tom    40     95    male

In [11]:
mydf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Grade   4 non-null      int64
 3   Sex     4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [12]:
mydf.describe()

             Age  Grade
count   4.000000   4.00
mean   27.250000  86.75
std     9.844626   8.50
min    19.000000  75.00
25%    19.750000  84.00
50%    25.000000  88.50
75%    32.500000  91.25
max    40.000000  95.00

In [16]:
#using arr.delete()

print(np.delete(mydf2, 1, axis = 0))
print(np.array(mydf2))

[[19 90 'female']
 [30 75 'male']
 [40 95 'male']]
[[19 90 'female']
 [20 87 'female']
 [30 75 'male']
 [40 95 'male']]

In [19]:
arr1 = np.array([[1,2],[3,4])
print(arr1)
print(arr1[1:0])

[[1 2]
 [3 4]]
3

In [25]:
arr2 = np.array([[1,5,2],[10,3,4], [4,6,1]])
print(arr2)
print(np.sort(arr2, axis = 1))
print(arr2)

[[ 1  5  2]
 [10  3  4]
 [ 4  6  1]]
[[ 1  2  5]
 [ 3  4 10]
 [ 1  4  6]]
[[ 1  5  2]
 [10  3  4]
 [ 4  6  1]]

In [26]:
print(np.sort(arr2, axis = None))

[ 1  1  2  3  4  4  5  6 10]

In [30]:
sarr = np.array([['Superman', 'Batman', 'Jim Hammond', 'Captain America', 'Green Arrow'],
               ['Aquaman', 'Wonder Woman', 'Martian Manhunter', 'Barry Allen', 'Hal Jordan'],
               ['Hawkman', 'Ray Palmer', 'Spider Man', 'Thor', 'Hank Pym'],
               ['Solar', 'Iron Man', 'Dr. Strange', 'Daredevil', 'Ted Kord'],
               ['Captian Marvel', 'Black Panther', 'Wolverine', 'Booster Gold', 'Spawn']])
print(sarr, "\n\n\n")
print(sarr[:,0])
print(sarr[2])
print(sarr[-1, 2])
print(sarr[1:4, 1:4])

[['Superman' 'Batman' 'Jim Hammond' 'Captain America' 'Green Arrow']
 ['Aquaman' 'Wonder Woman' 'Martian Manhunter' 'Barry Allen' 'Hal Jordan']
 ['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
 ['Solar' 'Iron Man' 'Dr. Strange' 'Daredevil' 'Ted Kord']
 ['Captian Marvel' 'Black Panther' 'Wolverine' 'Booster Gold' 'Spawn']]



['Superman' 'Aquaman' 'Hawkman' 'Solar' 'Captian Marvel']
['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
Wolverine
[['Wonder Woman' 'Martian Manhunter' 'Barry Allen']
 ['Ray Palmer' 'Spider Man' 'Thor']
 ['Iron Man' 'Dr. Strange' 'Daredevil']]

In [31]:
print(sarr.shape)

(5, 5)

In [54]:
#Temperature Problem
temp_data = np.random.randint(2, 10, (2, 10))
temp_data_f = temp_data*1.8 + 32

avg_temp = np.mean(temp_data_f, axis = 1)
sensor_idx = np.argmax(avg_temp)


k = 3
pad = (k//2, k//2)
temp_data_f_padded = np.pad(temp_data_f, [(0,0), pad], mode = 'edge')
print(temp_data_f)
print(temp_data_f_padded)

kernel = np.ones(k) / k
temp_data_f_moving_avg = np.apply_along_axis(lambda x: np.convolve(x, kernel, mode='valid'), axis=1, arr=temp_data_f_padded)

print(temp_data_f_moving_avg)

[[44.6 37.4 44.6 39.2 41.  41.  37.4 44.6 37.4 48.2]
 [48.2 39.2 44.6 48.2 44.6 46.4 48.2 46.4 48.2 35.6]]
[[44.6 44.6 37.4 44.6 39.2 41.  41.  37.4 44.6 37.4 48.2 48.2]
 [48.2 48.2 39.2 44.6 48.2 44.6 46.4 48.2 46.4 48.2 35.6 35.6]]
[[42.2 42.2 40.4 41.6 40.4 39.8 41.  39.8 43.4 44.6]
 [45.2 44.  44.  45.8 46.4 46.4 47.  47.6 43.4 39.8]]

## Linear Algebra Numpy

In [3]:
import numpy as np
from numpy.linalg import norm

In [4]:
# column and row vectors:
c_vec = np.array([[1,6,7,3]])
r_vec = np.array([[1], [2],[5], [6]])

print(c_vec,'\n\n', r_vec)

[[1 6 7 3]]

 [[1]
 [2]
 [5]
 [6]]

In [5]:
new_vec = c_vec.T
print(new_vec)

[[1]
 [6]
 [7]
 [3]]

In [12]:
norm_1_1 = norm(c_vec, 1)
norm_1_2 = norm(c_vec, 2)
norm_1_inf = norm(c_vec, np.inf,)

print(f"order of 1: {norm_1_1}, order of 2: {norm_1_2}, order of infinity: {norm_1_inf}")

order of 1: 7.0, order of 2: 9.746794344808965, order of infinity: 17.0

In [19]:
# finding theta:
arr1 = np.array([[1,4,3]])
arr2 = np.array([[4,-9,7]])
arr2_t = arr2.T

print(np.cross(arr1, arr2))

[[ 55   5 -25]]