# <font color=orange> Correlation and Causality </font>

**MACHINE LEARNING**

#### What is Machine Learning?

 In 1959, Arthur Samuel, a computer scientist who pioneered the study of artificial intelligence, described machine learning as “the study that gives computers the ability to learn without being explicitly programmed.”

 Alan Turing’s seminal paper (Turing, 1950) introduced a benchmark standard for demonstrating machine intelligence, such that a machine has to be intelligent and responsive in a manner that cannot be differentiated from that of a human being. "Machine Learning is an application of artificial intelligence where a computer/machine learns from the past experiences (input data) and makes future predictions. The performance of such a system should be at least human level."


#### Machine Learning Categories
 Machine Learning is generally categorized into three types: Supervised Learning, Unsupervised Learning, Reinforcement learning

##### Supervised Learning:
 In supervised learning the machine experiences the examples along with the labels or targets for each example. The labels in the data help the algorithm to correlate the features.

 Two of the most common supervised machine learning tasks are **classification** and **regression**.

 In regression problems the machine must predict the value of a continuous response variable. Examples of regression problems include predicting the sales for a new product, or the salary for a job based on its description.

 In classification problems the machine must learn to predict discrete values. That is, the machine must predict the most probable category, class, or label for new examples. Applications of classification include predicting whether a stock's price will rise or fall, or deciding if a news article belongs to the politics or leisure section.

# Correlation:


> In statistics, correlation or dependence is any statistical relationship, whether causal or not, between two random variables or bivariate data. In the broadest sense correlation is any statistical association, though it commonly refers to the degree to which a pair of variables are linearly related.
- Wikipedia (https://en.wikipedia.org/wiki/Correlation)

___
## How is correlation measured?

**For two variables, a statistical correlation is measured by the use of a Correlation Coefficient. The correlation coefficient is the specific measure that quantifies the strength of the linear relationship between two variables in a correlation analysis. The coefficient is what we symbolize with the r in a correlation report.**

### How do we calculate the correlation coefficient? 

#### The sample correlation coefficient can be represented with a formula:
![](https://editor.analyticsvidhya.com/uploads/39170Formula.JPG) <br>

**For two variables, the formula compares the distance of each datapoint from the variable mean and uses this to tell us how closely the relationship between the variables can be fit to an imaginary line drawn through the data. This is what we mean when we say that correlations look at linear relationships.**



### What do the values of the correlation coefficient mean?

#### The correlation coefficient r is a unit-free value between -1 and 1. Correlations are typically written with the r number:

- The closer r is to zero, the weaker the linear relationship.
- Positive r values indicate a positive correlation, where the values of both variables tend to increase together.
- Negative r values indicate a negative correlation, where the values of one variable tend to increase when the values of the other variable decrease.
- The values 1 and -1 both represent "perfect" correlations, positive and negative respectively. Two perfectly correlated variables change together at a fixed rate. We say they have a linear relationship; when plotted on a scatterplot, all data points can be connected with a straight line.

![](https://miro.medium.com/max/1202/1*TVORzUJdW8s2cmNreDyZWw.png) <br>



### Strong and weak correlations:

![](https://qi.elft.nhs.uk/wp-content/uploads/2014/08/scatter-plot-31.png)

Note: If the dots in the scatter plot are situated densely, the correlation between the two variables is high; and if they are located sparsely, the correlation is weak.

## This table helps with interpreting r values:
.

.




![](https://www.researchgate.net/profile/Mahiswaran-Selvanathan/publication/345693737/figure/tbl1/AS:956412914040832@1605038016475/The-scale-of-Pearsons-Correlation-Coefficient.png) <br>

## Example 1:

### Let's use the imdb dataset and see how we can calculate the correlation coefficient:

In [1]:
import pandas as pd

df = pd.read_csv("IMDB.csv")
df.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'IMDB.csv'

In [ ]:
# To find the correlation among the columns using pearson method
df.corr(method ='pearson')

## Example 2: 

### Let us consider the housing price dataset

In [2]:
import pandas as pd
housing= pd.read_csv("USA_Housing.csv")
housing

,Area Income,Area House Age,Area Population,Price,Address
0,79545,5.68,23087,1059034,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79249,6.00,40173,1505891,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287,5.87,36882,1058988,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345,7.19,34310,1260617,USS Barnett\nFPO AP 44820
4,59982,5.04,26354,630943,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...
4995,60568,7.83,22837,1060194,USNS Williams\nFPO AP 30153-7653
4996,78491,7.00,25616,1482618,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63391,7.25,33266,1030730,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001,5.53,42626,1198657,USS Wallace\nFPO AE 73316
4999,65511,5.99,46501,1298950,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [3]:
housing.iloc[:,:4].corr()

                 Area Income  Area House Age  Area Population     Price
Area Income         1.000000       -0.001997        -0.016234  0.639734
Area House Age     -0.001997        1.000000        -0.018731  0.452575
Area Population    -0.016234       -0.018731         1.000000  0.408556
Price               0.639734        0.452575         0.408556  1.000000


# Causality:


> Causality (also referred to as causation, or cause and effect) is influence by which one event, process, state or object (a cause) contributes to the production of another event, process, state or object (an effect) where the cause is partly responsible for the effect, and the effect is partly dependent on the cause.
- Wikipedia (https://en.wikipedia.org/wiki/Causality)

### Relationships: Correlation and Causality

#### In this lecture, we want to talk about the relationships between different actions. Think about these examples:

- Action A:"Throwing a ball" and Action B:"Breaking a window" <br>
- Action A:"Studying hard for an exam" and Action B:"Getting a good grade" <br>
- Action A:"Smoking" and Action B:"Alcoholism" <br>
- Action A:"Drinking hot lava" and Action B:"Death" <br>
- Action A:"Eating ice cream" and Action B:"Death due to drowning" <br>

#### What do you think is the relationship between Action A and Action B in each case?

___

#### Two or more variables are considered to be related, in a statistical context, if their values depend on each other: As the value of one variable increases or decreases so does the value of the other variable (although it may be in the opposite direction). For example, for the two variables "hours worked" and "income earned" there is a relationship between the two if the increase in hours worked is associated with an increase in income earned. If we consider the two variables "price" and "purchasing power", as the price of goods increases a person's ability to buy these goods decreases (assuming a constant income).

#### Correlation is a statistical measure (expressed as a number) that describes the size and direction of a relationship between two or more variables. A correlation between variables, however, does not automatically mean that the change in one variable is the cause of the change in the values of the other variable.

#### Causation indicates that one event is the result of the occurrence of the other event; i.e. there is a causal relationship between the two events. This is also referred to as cause and effect.

#### Theoretically, the difference between the two types of relationships are easy to identify — an action or occurrence can cause another (e.g. smoking causes an increase in the risk of developing lung cancer), or it can correlate with another (e.g. smoking is correlated with alcoholism, but it does not cause alcoholism). In practice, however, it remains difficult to clearly establish cause and effect, compared with establishing correlation.

___

#### Check out these examples:

![](https://miro.medium.com/max/1200/1*8j7U89RK1SgopIGET0mSFA.png) <br>


#### Or this one:

![](https://d35fo82fjcw0y8.cloudfront.net/2018/07/05092148/correlation-vs-causation-phone-RAM1-1024x574.png) <br>

#### Here is an interesting visual:

![](https://www.eufic.org/images/uploads/understanding-science/Correlation_Vs_Causation_-_2019-en.png) <br>

#### And that is exactly why we care about the difference of causality and correlation:

![](https://images.ctfassets.net/vrkkgjbn4fsk/6zStaOhyU0II1ktEbqsFUN/1504e23f790afdda052f3516b8bc1089/correlation-vs-causation.png) <br>

#### The objective of much research or scientific analysis is to identify the extent to which one variable relates to another variable. For example:
- Is there a relationship between a person's education level and their health?
- Is pet ownership associated with living longer?
- Did a company's marketing campaign increase their product sales?

#### These and other questions are exploring whether a correlation exists between the two variables, and if there is a correlation then this may guide further research into investigating whether one action causes the other. By understanding correlation and causality, it allows for policies and programs that aim to bring about a desired outcome to be better targeted.

___
## How can causation be established?

#### Causality is the area of statistics that is commonly misunderstood and misused by people in the mistaken belief that because the data shows a correlation that there is necessarily an underlying causal relationship

#### The use of a controlled study is the most effective way of establishing causality between variables. In a controlled study, the sample or population is split in two, with both groups being comparable in almost every way. The two groups then receive different treatments, and the outcomes of each group are assessed. For example, in medical research, one group may receive a placebo while the other group is given a new type of medication. If the two groups have noticeably different outcomes, the different experiences may have caused the different outcomes.

![](https://bigdata-madesimple.com/wp-content/uploads/2016/05/correlation.png) <br>